import { APPLICATION_STATUSES } from './statuses'

export const demoApplications = [
  {
    _id: 'demo-cwg-uiux',
    companyName: 'CWG',
    jobTitle: 'UI/UX Intern',
    status: APPLICATION_STATUSES.INTERVIEW,
    dateApplied: '2026-05-28',
    followUpDate: '2026-06-08',
    applicationDeadline: '2026-06-20',
    applicationSource: 'LinkedIn',
    salaryMin: 120000,
    salaryMax: 180000,
    salaryCurrency: 'NGN',
    cvUsed: 'UI/UX CV',
    recruiterName: 'Ada Okafor',
    recruiterEmail: 'ada.okafor@cwg.example',
    createdAt: '2026-06-05T09:00:00.000Z',
  },
  {
    _id: 'demo-fiberone-frontend',
    companyName: 'FiberOne',
    jobTitle: 'Frontend Intern',
    status: APPLICATION_STATUSES.APPLIED,
    dateApplied: '2026-05-30',
    followUpDate: '2026-06-06',
    applicationDeadline: '2026-06-18',
    applicationSource: 'Company Website',
    salaryMin: 100000,
    salaryMax: 150000,
    salaryCurrency: 'NGN',
    cvUsed: 'Frontend CV',
    recruiterName: 'Timi Bello',
    recruiterEmail: 'talent@fiberone.example',
    createdAt: '2026-06-04T10:30:00.000Z',
  },
  {
    _id: 'demo-andela-junior',
    companyName: 'Andela',
    jobTitle: 'Junior Developer',
    status: APPLICATION_STATUSES.ASSESSMENT,
    dateApplied: '2026-06-01',
    followUpDate: '2026-06-10',
    applicationDeadline: '2026-06-22',
    applicationSource: 'Referral',
    salaryMin: 180000,
    salaryMax: 260000,
    salaryCurrency: 'NGN',
    cvUsed: 'Frontend CV',
    recruiterName: 'Grace Musa',
    recruiterEmail: 'grace.musa@andela.example',
    createdAt: '2026-06-03T13:45:00.000Z',
  },
  {
    _id: 'demo-kuda-product',
    companyName: 'Kuda',
    jobTitle: 'Product Design Intern',
    status: APPLICATION_STATUSES.PENDING,
    dateApplied: '2026-06-03',
    followUpDate: '2026-06-12',
    applicationDeadline: '2026-06-25',
    applicationSource: 'Indeed',
    salaryMin: 130000,
    salaryMax: 180000,
    salaryCurrency: 'NGN',
    cvUsed: 'UI/UX CV',
    recruiterName: 'Kemi Yusuf',
    createdAt: '2026-06-02T11:00:00.000Z',
  },
  {
    _id: 'demo-paystack-growth',
    companyName: 'Paystack',
    jobTitle: 'Growth Intern',
    status: APPLICATION_STATUSES.OFFER,
    dateApplied: '2026-05-22',
    followUpDate: '2026-06-02',
    applicationDeadline: '2026-06-14',
    applicationSource: 'LinkedIn',
    salaryMin: 200000,
    salaryMax: 280000,
    salaryCurrency: 'NGN',
    cvUsed: 'General Internship CV',
    recruiterName: 'Ife Thomas',
    createdAt: '2026-05-31T15:20:00.000Z',
  },
  {
    _id: 'demo-mono-qa',
    companyName: 'Mono',
    jobTitle: 'QA Intern',
    status: APPLICATION_STATUSES.REJECTED,
    dateApplied: '2026-05-18',
    applicationDeadline: '2026-05-30',
    applicationSource: 'Company Website',
    salaryMin: 90000,
    salaryMax: 130000,
    salaryCurrency: 'NGN',
    cvUsed: 'General Internship CV',
    rejectionReason: 'Role required more automated testing experience.',
    createdAt: '2026-05-25T08:15:00.000Z',
  },
]

export const demoInterviews = [
  {
    _id: 'demo-interview-cwg',
    applicationId: 'demo-cwg-uiux',
    companyName: 'CWG',
    jobTitle: 'UI/UX Intern',
    date: '2026-06-10',
    time: '10:00',
    interviewType: 'Portfolio Review',
    interviewLink: 'https://meet.example.com/cwg-uiux',
    location: 'Google Meet',
    preparationNotes: 'Prepare Figma case study, explain design decisions, and bring usability testing notes.',
    outcome: 'scheduled',
  },
  {
    _id: 'demo-interview-andela',
    applicationId: 'demo-andela-junior',
    companyName: 'Andela',
    jobTitle: 'Junior Developer',
    date: '2026-06-12',
    time: '14:30',
    interviewType: 'Technical Interview',
    interviewLink: 'https://meet.example.com/andela-tech',
    location: 'Zoom',
    preparationNotes: 'Review React state, API calls, arrays, objects, and explain InternTrack project structure.',
    outcome: 'scheduled',
  },
  {
    _id: 'demo-interview-fiberone',
    applicationId: 'demo-fiberone-frontend',
    companyName: 'FiberOne',
    jobTitle: 'Frontend Intern',
    date: '2026-06-14',
    time: '11:30',
    interviewType: 'HR Screening',
    interviewLink: 'https://meet.example.com/fiberone-hr',
    location: 'Microsoft Teams',
    preparationNotes: 'Prepare availability, salary expectation, portfolio link, and why FiberOne.',
    outcome: 'scheduled',
  },
]

export const demoDocuments = [
  {
    _id: 'demo-doc-uiux',
    fileName: 'UI/UX CV',
    documentType: 'CV',
    cvType: 'Design',
    usedCount: 2,
    uploadedAt: '2026-06-01',
    linkedApplicationId: { companyName: 'CWG', jobTitle: 'UI/UX Intern' },
    versionHistory: [{ version: 1 }],
  },
  {
    _id: 'demo-doc-frontend',
    fileName: 'Frontend CV',
    documentType: 'CV',
    cvType: 'Frontend',
    usedCount: 2,
    uploadedAt: '2026-06-02',
    linkedApplicationId: { companyName: 'FiberOne', jobTitle: 'Frontend Intern' },
    versionHistory: [{ version: 1 }, { version: 2 }],
  },
  {
    _id: 'demo-doc-general',
    fileName: 'General Internship CV',
    documentType: 'CV',
    cvType: 'General',
    usedCount: 2,
    uploadedAt: '2026-06-03',
    linkedApplicationId: { companyName: 'Paystack', jobTitle: 'Growth Intern' },
    versionHistory: [{ version: 1 }],
  },
]

const followUpStatuses = [
  APPLICATION_STATUSES.PENDING,
  APPLICATION_STATUSES.APPLIED,
  APPLICATION_STATUSES.ASSESSMENT,
  APPLICATION_STATUSES.INTERVIEW,
]

export const demoFollowUps = demoApplications
  .filter((application) => application.followUpDate && followUpStatuses.includes(application.status))
  .map((application) => ({
    _id: `${application._id}-follow-up`,
    companyName: application.companyName,
    jobTitle: application.jobTitle,
    followUpDate: application.followUpDate,
    message: `${application.companyName} - ${application.jobTitle} needs a recruiter follow-up.`,
  }))

export const demoNotifications = [
  ...demoFollowUps.map((application) => ({
    id: `demo-notification-${application._id}`,
    type: 'follow-up',
    title: `Follow up with ${application.companyName}`,
    message: application.message,
    dueDate: application.followUpDate,
    href: '/applications',
  })),
  {
    id: 'demo-notification-cwg-interview',
    type: 'interview',
    title: 'CWG interview coming up',
    message: 'Portfolio Review for UI/UX Intern is scheduled for 10:00 AM.',
    dueDate: '2026-06-10',
    href: '/interviews',
  },
  {
    id: 'demo-notification-cv',
    type: 'deadline',
    title: 'Update Frontend CV',
    message: 'Your Frontend CV is used by FiberOne and Andela. Keep the latest project links updated.',
    dueDate: '2026-06-08',
    href: '/documents',
  },
]

export const demoAnalytics = {
  totalApplications: demoApplications.length,
  pending: 1,
  interviews: demoInterviews.length,
  offers: 1,
  rejections: 1,
  ghosted: 0,
  followUpsDue: demoFollowUps.length,
  responseRate: 67,
  offerRate: 17,
  interviewConversionRate: 50,
  statusBreakdown: {
    [APPLICATION_STATUSES.PENDING]: 1,
    [APPLICATION_STATUSES.APPLIED]: 1,
    [APPLICATION_STATUSES.ASSESSMENT]: 1,
    [APPLICATION_STATUSES.INTERVIEW]: 1,
    [APPLICATION_STATUSES.OFFER]: 1,
    [APPLICATION_STATUSES.REJECTED]: 1,
    [APPLICATION_STATUSES.GHOSTED]: 0,
  },
  monthlyApplications: [
    { month: 'March', count: 2 },
    { month: 'April', count: 3 },
    { month: 'May', count: 5 },
    { month: 'June', count: 6 },
  ],
  bestPerformingCVs: [
    { cv: 'Frontend CV', responseRate: 75, applications: 2 },
    { cv: 'UI/UX CV', responseRate: 50, applications: 2 },
    { cv: 'General Internship CV', responseRate: 50, applications: 2 },
  ],
  companyResponseRankings: [
    { company: 'CWG', responseRate: 100, responses: 1 },
    { company: 'Andela', responseRate: 100, responses: 1 },
    { company: 'Paystack', responseRate: 100, responses: 1 },
    { company: 'FiberOne', responseRate: 0, responses: 0 },
  ],
}
